require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 12

Metrics/ParameterLists:
  Max: 5
  MaxOptionalParameters: 8
  CountKeywordArgs: false

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'lib/brapi/models/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

RSpec/MultipleExpectations:
  Max: 8

RSpec/ExampleLength:
  Max: 25

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 8
